networks:
  test:
    name: fabric_test
services:
  

  orderer.patient.com:
    command: orderer
    container_name: orderer.patient.com
    environment:
    - FABRIC_LOGGING_SPEC=INFO
    - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
    - ORDERER_GENERAL_LISTENPORT=7060
    - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
    - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    - ORDERER_GENERAL_TLS_ENABLED=true
    - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
    - ORDERER_CHANNELPARTICIPATION_ENABLED=true
    - ORDERER_ADMIN_TLS_ENABLED=true
    - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
    - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
    - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7153
    - ORDERER_OPERATIONS_LISTENADDRESS=orderer.patient.com:9442
    - ORDERER_METRICS_PROVIDER=prometheus
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    networks:
    - test
    ports:
    - 7060:7060
    - 7153:7153
    - 9442:9442
    volumes:
    - ../organizations/ordererOrganizations/patient.com/orderers/orderer.patient.com/msp:/var/hyperledger/orderer/msp
    - ../organizations/ordererOrganizations/patient.com/orderers/orderer.patient.com/tls/:/var/hyperledger/orderer/tls
    - orderer.patient.com:/var/hyperledger/production/orderer
    working_dir: /root
  
volumes:
  orderer.patient.com: null

  
