networks:
  test:
    name: fabric_test
services:
  cli:
    command: /bin/bash
    container_name: cli
    depends_on:
    - peer0.patorg.patient.com
    environment:
    - GOPATH=/opt/gopath
    - FABRIC_LOGGING_SPEC=INFO
    - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
    - CORE_PEER_TLS_ENABLED=true
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    networks:
    - test
    stdin_open: true
    tty: true
    volumes:
    - ../organizations:/etc/hyperledger/fabric/peer/organizations
    - ../../../DoctorNodeCreater/network/organizations:/etc/hyperledger/fabric/peer/doctorOrganization
    - ../scripts:/etc/hyperledger/fabric/peer/scripts/
    - ./docker/peercfg:/etc/hyperledger/peercfg
    working_dir: /etc/hyperledger/fabric/peer
  peer0.patorg.patient.com:
    command: peer node start
    container_name: peer0.patorg.patient.com
    environment:
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_PROFILE_ENABLED=false
    - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    - CORE_PEER_ID=peer0.patorg.patient.com
    - CORE_PEER_ADDRESS=peer0.patorg.patient.com:${PEER_PATIENT_PORT}
    - CORE_PEER_LISTENADDRESS=0.0.0.0:${PEER_PATIENT_PORT}
    - CORE_PEER_CHAINCODEADDRESS=peer0.patorg.patient.com:${NEXT_PEER_PORT_CC}
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${NEXT_PEER_PORT_CC}
    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.patorg.patient.com:${PEER_PATIENT_PORT}
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.patorg.patient.com:${PEER_PATIENT_PORT}
    - CORE_PEER_LOCALMSPID=PatOrgMSP
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    - CORE_OPERATIONS_LISTENADDRESS=peer0.patorg.patient.com:${OPER_LISTEN_PORT}
    - CORE_METRICS_PROVIDER=prometheus
    - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0patorg"}
    - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    networks:
    - test
    ports:
    - ${PEER_PATIENT_PORT}:${PEER_PATIENT_PORT}
    - ${OPER_LISTEN_PORT}:${OPER_LISTEN_PORT}
    volumes:
    - ../organizations/peerOrganizations/patorg.patient.com/peers/peer0.patorg.patient.com:/etc/hyperledger/fabric
    - peer0.patorg.patient.com:/var/hyperledger/production
    - ./docker/peercfg:/etc/hyperledger/peercfg
    - ${DOCKER_SOCK}:/host/var/run/docker.sock
    working_dir: /root
volumes:
  peer0.patorg.patient.com: null
