global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderer"
    static_configs:
      - targets: ["orderer.patient.com:9442"]
  - job_name: "peer${PEER_PATIENT_NUMBER}_patorg"
    static_configs:
      - targets: ["peer${PEER_PATIENT_NUMBER}.patorg.patient.com:${OPER_LISTEN_PORT}"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
